### ISSUE TITLE
SetConsoleTitle应改为宽字节版本

### ISSUE THREAD

**Issue by int2e** [vczh-libraries/Vlpp#7]
#if defined VCZH_MSVC
			SetConsoleTitle(string.Buffer());
#endif
应该改为
SetConsoleTitleW

**Comment by vczh** [comment]
默认就是W的，我不支持编译为ANSI的选项

**Comment by int2e** [comment]
但是现在只有这个会影响ANSI编译,其他并不影响

**Comment by vczh** [comment]
首先，虽然Vlpp只有这一处，但是这个org下用到API的地方多了去了。
其次，如果编译我的代码的时候不要用ANSI就最好了，我不喜欢人们用ANSI。
